services:
  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:7.0.7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  lgtm:
    image: grafana/otel-lgtm:0.11.0
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

volumes:
  mongodb_data:
  postgres_data:
