version: "3.8"
# Pinned to latest semantic versions as of 2025-04-17
services:
  redis:
    image: redis:7.2.12
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:7.0.7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  loki:
    image: grafana/loki:2.10.0
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:1.10.0
    ports:
      - "3200:3200"

  mimir:
    image: grafana/mimir:2.10.0
    ports:
      - "9095:9095"

  grafana:
    image: grafana/grafana:11.1.2
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - tempo
      - mimir

volumes:
  mongodb_data:
  postgres_data: