# This rule is not used by the project entitlements itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the inventory.synapse.platform.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: entitlements
    app.kubernetes.io/managed-by: kustomize
  name: entitlement-editor-role
rules:
- apiGroups:
  - inventory.synapse.platform.io
  resources:
  - entitlements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inventory.synapse.platform.io
  resources:
  - entitlements/status
  verbs:
  - get
