# This rule is not used by the project entitlements itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to inventory.synapse.platform.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: entitlements
    app.kubernetes.io/managed-by: kustomize
  name: entitlement-viewer-role
rules:
- apiGroups:
  - inventory.synapse.platform.io
  resources:
  - entitlements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inventory.synapse.platform.io
  resources:
  - entitlements/status
  verbs:
  - get
