# This rule is not used by the project entitlements itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over inventory.synapse.platform.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: entitlements
    app.kubernetes.io/managed-by: kustomize
  name: entitlement-admin-role
rules:
- apiGroups:
  - inventory.synapse.platform.io
  resources:
  - entitlements
  verbs:
  - '*'
- apiGroups:
  - inventory.synapse.platform.io
  resources:
  - entitlements/status
  verbs:
  - get
